version: '2.4'

services:
  database:
    image: postgres:12-alpine
    container_name: template-database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.db/data:/var/lib/postgresql/data:delegated
      - ./.db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  api:
    build:
      context: .
      target: dev
    container_name: template-api
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./dist:/app/dist:delegated
      - ./docs:/app/docs:delegated
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/layered-tpl-development
      - PORT=3000
    ports:
      - 3000:3000
      - 9222:9222
