version: '2.4'

services:
  database:
    image: postgres:12-alpine
    container_name: database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

    # volumes:
      # - ./.db/data:/var/lib/postgresql/data:delegated
      # - ./.db/init:/docker-entrypoint-initdb.d

    volumes:
      - pgdata:/data/postgres
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s


  api:
    build:
      context: .
      target: dev
    container_name: travelplans-api
    depends_on:
      - database
    volumes:
      - .:/usr/app
      # - ./dist:/app/dist:delegated
      # - ./docs:/app/docs:delegated

      # environment:
        # - DATABASE_URL=postgres://postgres:postgres@database:5432/layered-tpl-development
        # - PORT=3000

    links:
      - database
    ports:
      - 3000:3000
      # - 9222:9222

volumes:
  pgdata:
    driver: local
